<?php

/**
 * @file
 * Module file for odp_base module.
 */

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Hiding local tabs for developer role only.
 */
function odp_base_menu_local_tasks_alter(&$data, $route_name) {
  if ($route_name == 'search.view_node_search') {
    unset($data['tabs'][0]);
  }
  if (FALSE == \Drupal::service('odp_user.organisation')->checkAccess(TRUE)) {
    if (in_array($route_name, ['entity.node.edit_form', 'entity.node.canonical'])) {
      unset($data['tabs'][0]);
    }
  }

  // Hide local tabs for anonymous user from node pages.
  $user_roles = \Drupal::service('odp_login_redirect.redirect_service')->getUserRoles();
  if (in_array($route_name, ['entity.node.canonical']) && in_array('anonymous', $user_roles['system_roles'])) {
    unset($data['tabs'][0]);
  }
}
