<?php

/**
 * @file
 * odp_taxonomy module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function odp_taxonomy_form_alter(&$form,
  FormStateInterface $form_state,
  $form_id) {
  if ($form_id == 'taxonomy_term_organisation_form') {
    $type = empty($form['tid']['#value']) ? 'Add' : 'Edit';
    $vocab = $form_state->getStorage()['taxonomy']['vocabulary']->get('name');
    $form['#title'] = t('<em>@type</em> @name', [
      '@type' => $type,
      '@name' => $vocab,
    ]);
  }

  if ($form_id == 'field_config_edit_form') {
    if ($form['#entity']->bundle() == 'api_document') {
      $config = \Drupal::config('odp_taxonomy.api_default_values');
      // Set the environment field of API from the config.
      if ($form['default_value']['widget']['#field_name'] == 'field_environment') {
        $form['default_value']['widget']['#default_value'] = $config->get('api_environment');
      }
      // Set the version field of API from the config.
      if ($form['default_value']['widget']['#field_name'] == 'field_api_version') {
        $form['default_value']['widget']['#default_value'] = $config->get('api_version');
      }
    }
  }
}
