<?php

/**
 * @file
 * Install, update and uninstall functions for the developer_portal installation profile.
 */

use Drupal\user\Entity\User;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function openapix_portal_install() {
	// Assign user 1 the "administrator" role.
  $user = User::load(1);
  $user->roles[] = 'administrator';
  $user->save();
  // Can add code in here to make nodes, terms, etc.
}
