<?php

/**
 * @file
 * Developer portal content module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\odp_node\ContentInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_entity_view_mode_alter().
 */
function odp_content_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  $current_user_role = \Drupal::currentUser()->getRoles();
  if ($entity->getEntityTypeId() == 'node') {
    // Change the node display mode of product.
    if ($entity->bundle() == 'api_product' && $view_mode == 'full') {
      $view_mode = $entity->get('field_view_mode')->getValue()[0]['value'];
    }

    // Change the node display mode of applications for anonymous user.
    elseif ($entity->bundle() == 'apps' && in_array('anonymous', $current_user_role)) {
      $view_mode = 'anonymous_user_content';
    }
  }
}

/**
 * Implements hook_entity_form_display_alter().
 */
function odp_content_entity_form_display_alter(&$form_display, $context) {
  $current_user_role = \Drupal::currentUser()->getRoles();
  // Change the node form display for developer role.
  if ($context['entity_type'] == 'node' && in_array('developer', $current_user_role)) {
    $id = $context['entity_type'] . '.' . $context['bundle'] . '.developer';
    $storage = \Drupal::entityManager()->getStorage('entity_form_display');
    $change_display = $storage->load($id);
    if ($change_display) {
      $form_display = $change_display;
    }
  }
}

/**
 * Preprocess page title.
 */
function odp_theme_preprocess_page_title(&$variables) {
  // Remove the page title from the content listing page.
  $current_path = \Drupal::service('path.current')->getPath();
  $path_index = explode('/', $current_path);
  if ((isset($path_index[3]) && in_array($path_index[3], ContentInterface::CONTENT_TYPES)) || $path_index[1] == 'forum') {
    $variables['title'] = '';
  }
}

/**
 * Implements hook_form_alter().
 */
function odp_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ContentInterface::FORM_IDS)) {
    $type = $form_state->getFormObject()->getEntity()->bundle();
    $label = NodeType::load($type)->label();
    $summary = $form['body']['widget'][0]['summary']['#title']->getUntranslatedString();
    $form['body']['widget'][0]['summary']['#title'] = t($label . ' ' . $summary);
  }
}
