<?php

/**
 * @file
 * Developer portal content module file.
 */

/**
 * Implements hook_entity_form_display_alter().
 */
function odp_content_entity_form_display_alter(&$form_display, $context) {
  $current_user_role = \Drupal::currentUser()->getRoles();
  // Change the node form display for developer role.
  if ($context['entity_type'] == 'node' && in_array('developer', $current_user_role)) {
    $id = $context['entity_type'] . '.' . $context['bundle'] . '.developer';
    $storage = \Drupal::entityManager()->getStorage('entity_form_display');
    $change_display = $storage->load($id);
    if ($change_display) {
      $form_display = $change_display;
    }
  }
}
