<?php

/**
 * @file
 * Async API module file.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function odp_asyncapi_views_pre_render(ViewExecutable $view) {
  $api_type = isset($view->result[0]->_entity->field_api_type) ?
    $view->result[0]->_entity->field_api_type->value : '';
  if ($view->storage->id() == 'api_document_formatter' &&
  isset($view->field['field_document']) &&
  $api_type == 'async') {
    $view->field['field_document']->options['type'] = $api_type;
  }
}

/**
 * Implements hook_theme().
 */
function odp_asyncapi_theme($existing, $type, $theme, $path) {
  return [
    'asyncapi_ui_field_item' => [
      'variables' => [],
    ],
  ];
}
