<?php

/**
 * @file
 * Module file opendevx_api.module.
 */

const OPENDEVX_API_OPTIONS = [
  'documents' => 'document_overview',
  'api-document' => 'api_document',
  'faqs' => 'faq',
  'products' => 'api_product',
  'landing-page' => 'listing_pages',
  'use-cases' => 'use_cases',
];

/**
 * Implements hook_views_query_alter().
 */
function opendevx_api_views_query_alter($view, $query) {
  if ($view->id() == 'content_listing_rest_resource' && $view->current_display == 'rest_export_1') {
    // Get the end point of the APIs.
    $path = \Drupal::request()->getpathInfo();
    $arg  = explode('/', $path);
    // Store the machine name of content types in an array of API urls.
    if (in_array($arg[3], array_keys(OPENDEVX_API_OPTIONS))) {
      $query->where[0]['conditions'][0]['value'] = OPENDEVX_API_OPTIONS[$arg[3]];
    }
  }
}
