<?php

/**
 * @file
 * OpenDevPortal Workflow module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_ID_alter().
 */
function odp_workflow_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {

  // Unset Application state key.
  if ($form['#id'] == 'views-exposed-form-proxies-listing-page-1') {
    unset($form['state']['#options']['Approval Workflow']);
  }

  // Unset Api state key.
  if ($form['#id'] == 'views-exposed-form-proxies-listing-page-2') {
    unset($form['state']['#options']['API Approval Workflow']);
  }
}

/**
 * Implements hook_form_alter().
 */
function odp_workflow_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Remove the unnecessary workflow values from the status filter.
  $request = \Drupal::request();
  if ($request->attributes->get('_route') == 'view.proxies_listing.page_3') {
    unset($form['state']['#options']['API Approval Workflow']);
    if (isset($form['state']['#options']['Approval Workflow']) && !empty($form['state']['#options']['Approval Workflow'])) {
      $form['state']['#options'] += $form['state']['#options']['Approval Workflow'];
      unset($form['state']['#options']['Approval Workflow']);
    }
  }
}
