<?php

/**
 * @file
 * Contains opendevx_login_redirect.module.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_user_login().
 */
function opendevx_login_redirect_user_login(AccountInterface $account) {
  \Drupal::service('opendevx_login_redirect.redirect_service')->setLoginDestination($account);
}

/**
 * Implements hook_user_logout().
 */
function opendevx_login_redirect_user_logout(AccountInterface $account) {
  \Drupal::service('opendevx_login_redirect.redirect_service')->setLogoutDestination($account);
}
