<?php

/**
 * Implements hook_theme().
 */
function odp_organisation_theme() {
  return [
    'front_organisation' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];
 }

/**
 * Implements hook_form_alter().
 */
function odp_organisation_form_alter(&$form,
\Drupal\Core\Form\FormStateInterface &$form_state,
$form_id) {
  switch ($form_id) {
    case 'taxonomy_term_organisation_form':
      $form['field_external_link']['#states'] = [
        'visible' => [
          ['select[name="field_refer_to"]' => ['value' => 'external']],
        ]
      ];
      $form['field_organisation_page']['#states'] = [
        'invisible' => [
          ['select[name="field_refer_to"]' => ['value' => '_none']],
        ]
      ];

    break;
  }
}
