<?php

/**
 * @file
 * Module file opendevx_navigation_block.module.
 */

/**
 * Implements hook_theme().
 */
function opendevx_navigation_block_theme() {
  return [
    'product_navigation' => [
      'variables' => [
        'navigationData' => NULL,
        'productTitle' => NULL,
      ],
    ],
    'dashboard_product_navigation' => [
      'variables' => [
        'navigationData' => NULL,
        'productTitle' => NULL,
      ],
    ],
  ];
}
