<?php

/**
 * Implements hook_theme().
 *
 */
function developer_portal_connector_theme($existing, $type, $theme, $path) {

  return [
    'developer_portal_connector_theme_programkeys' => [
      'render element' => 'children',
      'template' => 'developer-portal-connector--program-keys',
      // Optionally define path to Twig template files. Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
      // Optionally define variables that will be passed to the Twig template and set default values for them.
      'variables' => [
        'details' => [0, 0, 0],
      ],
    ],
  ];

}
