# Schema for the configuration files of the opendevx_theme Theme.

opendevx_theme.settings:
  type: theme_settings
  label: "opendevx_theme settings"
  mapping:

# Library.
# ----------------------------
opendevx_theme_library:
  type: text
  label: "Load library"

# Container.
# ----------------------------
opendevx_theme_fluid_container:
  type: integer
  label: "Fluid container"

# Region.
# ----------------------------
opendevx_theme_region_clean_top_header:
  type: text
  label: "Clean wrapper for Top header region"
opendevx_theme_region_class_top_header:
  type: text
  label: "Classes for Top header region"
opendevx_theme_region_clean_top_header_form:
  type: text
  label: "Clean wrapper for Top header form region"
opendevx_theme_region_class_top_header_form:
  type: text
  label: "Classes for Top header form region"
opendevx_theme_region_clean_header:
  type: text
  label: "Clean wrapper for Header region"
opendevx_theme_region_class_header:
  type: text
  label: "Classes for Header region"
opendevx_theme_region_clean_header_form:
  type: text
  label: "Clean wrapper for Header form region"
opendevx_theme_region_class_header_form:
  type: text
  label: "Classes for Header form region"
opendevx_theme_region_clean_primary_menu:
  type: text
  label: "Clean wrapper for Primary menu region"
opendevx_theme_region_class_primary_menu:
  type: text
  label: "Classes for Primary menu region"
opendevx_theme_region_clean_secondary_menu:
  type: text
  label: "Clean wrapper for Secondary menu region"
opendevx_theme_region_class_secondary_menu:
  type: text
  label: "Classes for Secondary menu region"
opendevx_theme_region_clean_page_top:
  type: text
  label: "Clean wrapper for Page top region"
opendevx_theme_region_class_page_top:
  type: text
  label: "Classes for Page top region"
opendevx_theme_region_clean_page_bottom:
  type: text
  label: "Clean wrapper for Page bottom region"
opendevx_theme_region_class_page_bottom:
  type: text
  label: "Classes for Page bottom region"
opendevx_theme_region_clean_highlighted:
  type: text
  label: "Clean wrapper for Highlighted region"
opendevx_theme_region_class_highlighted:
  type: text
  label: "Classes for Highlighted region"
opendevx_theme_region_clean_featured_top:
  type: text
  label: "Clean wrapper for Featured top region"
opendevx_theme_region_class_featured_top:
  type: text
  label: "Classes for Featured top region"
opendevx_theme_region_clean_breadcrumb:
  type: text
  label: "Clean wrapper for Breadcrumb region"
opendevx_theme_region_class_breadcrumb:
  type: text
  label: "Classes for Breadcrumb region"
opendevx_theme_region_clean_content:
  type: text
  label: "Clean wrapper for Content region"
opendevx_theme_region_class_content:
  type: text
  label: "Classes for Content region"
opendevx_theme_region_clean_sidebar_first:
  type: text
  label: "Clean wrapper for Sidebar first region"
opendevx_theme_region_class_sidebar_first:
  type: text
  label: "Classes for Sidebar first region"
opendevx_theme_region_clean_sidebar_second:
  type: text
  label: "Clean wrapper for Sidebar second region"
opendevx_theme_region_class_sidebar_second:
  type: text
  label: "Classes for Sidebar second region"
opendevx_theme_region_clean_featured_bottom_first:
  type: text
  label: "Clean wrapper for Featured bottom first region"
opendevx_theme_region_class_featured_bottom_first:
  type: text
  label: "Classes for Featured bottom first region"
opendevx_theme_region_clean_featured_bottom_second:
  type: text
  label: "Clean wrapper for Featured bottom second region"
opendevx_theme_region_class_featured_bottom_second:
  type: text
  label: "Classes for Featured bottom second region"
opendevx_theme_region_clean_featured_bottom_third:
  type: text
  label: "Clean wrapper for Featured bottom third region"
opendevx_theme_region_class_featured_bottom_third:
  type: text
  label: "Classes for Featured bottom third region"
opendevx_theme_region_clean_footer_first:
  type: text
  label: "Clean wrapper for Footer first region"
opendevx_theme_region_class_footer_first:
  type: text
  label: "Classes for Footer first region"
opendevx_theme_region_clean_footer_second:
  type: text
  label: "Clean wrapper for Footer second region"
opendevx_theme_region_class_footer_second:
  type: text
  label: "Classes for Footer second region"
opendevx_theme_region_clean_footer_third:
  type: text
  label: "Clean wrapper for Footer third region"
opendevx_theme_region_class_footer_third:
  type: text
  label: "Classes for Footer third region"
opendevx_theme_region_clean_footer_fourth:
  type: text
  label: "Clean wrapper for Footer fourth region"
opendevx_theme_region_class_footer_fourth:
  type: text
  label: "Classes for Footer fourth region"
opendevx_theme_region_clean_footer_fifth:
  type: text
  label: "Clean wrapper for Footer fifth region"
opendevx_theme_region_class_footer_fifth:
  type: text
  label: "Classes for Footer fifth region"

# Sidebar position.
# ----------------------------
opendevx_theme_sidebar_position:
  type: text
  label: "Sidebar position"
opendevx_theme_content_offset:
  type: integer
  label: "Content offset"

# Sidebar first layout.
# ----------------------------
opendevx_theme_sidebar_collapse:
  type: integer
  label: "Sidebar collapse"
opendevx_theme_sidebar_first_width:
  type: integer
  label: "Sidebar first width"
opendevx_theme_sidebar_first_offset:
  type: integer
  label: "Sidebar first offset"

# Sidebar second layout.
# ----------------------------
opendevx_theme_sidebar_second_width:
  type: integer
  label: "Sidebar second width"
opendevx_theme_sidebar_second_offset:
  type: integer
  label: "Sidebar second layout"

# Buttons.
# ----------------------------
opendevx_theme_button:
  type: integer
  label: "Convert input submit to button element"
opendevx_theme_button_size:
  type: text
  label: "Default button size"
opendevx_theme_button_outline:
  type: integer
  label: "Button with outline format"

# Navbar.
# ----------------------------
opendevx_theme_navbar_container:
  type: text
  label: "Navbar width container"
opendevx_theme_navbar_toggle:
  type: text
  label: "Navbar toggle size"
opendevx_theme_navbar_top_navbar:
  type: integer
  label: "Navbar top is navbar"
opendevx_theme_navbar_top_position:
  type: text
  label: "Navbar top position"
opendevx_theme_navbar_top_color:
  type: text
  label: "Navbar top link color"
opendevx_theme_navbar_top_background:
  type: text
  label: "Navbar top background color"
opendevx_theme_navbar_position:
  type: text
  label: "Navbar position"
opendevx_theme_navbar_color:
  type: text
  label: "Navbar link color"
opendevx_theme_navbar_background:
  type: text
  label: "Navbar background color"

# Messages.
# ----------------------------
opendevx_theme_messages_widget:
  type: text
  label: "Messages widget"

# Form.
# ----------------------------
opendevx_theme_radio:
  type: text
  label: "Radio widget"
opendevx_theme_checkbox:
  type: text
  label: "Checkbox widget"
opendevx_theme_select:
  type: text
  label: "Select widget"
opendevx_theme_file:
  type: text
  label: "File widget"

# Affix.
# ----------------------------
opendevx_theme_navbar_top_affix:
  type: integer
  label: "Affix navbar top"
opendevx_theme_navbar_affix:
  type: integer
  label: "Affix navbar"
opendevx_theme_sidebar_first_affix:
  type: integer
  label: "Affix sidebar first"
opendevx_theme_sidebar_second_affix:
  type: integer
  label: "Affix sidebar first"

# Scrollspy.
# ----------------------------
opendevx_theme_scroll_spy:
  type: text
  label: "Scrollspy element ID"

# Fonts.
# ----------------------------
opendevx_theme_google_fonts:
  type: text
  label: "Google Fonts combination"

# Icons.
# ----------------------------
opendevx_theme_icons:
  type: text
  label: "Icon set"

# System messages.
# ----------------------------
opendevx_theme_system_messages:
  type: text
  label: "System messages color scheme"

# Tables.
# ----------------------------
opendevx_theme_table_style:
  type: text
  label: "Table cell style"
opendevx_theme_table_hover:
  type: integer
  label: "Hover effect over table cells"
opendevx_theme_table_head:
  type: text
  label: "Table header color scheme"
