<?php

/**
 * @file
 * Voyager module file.
 */

use Drupal\views\ViewExecutable;
use Drupal\Core\Form\FormStateInterface;
use Drupal\opendevx_voyager\VoyagerInterface;

/**
 * Implements hook_views_pre_render().
 */
function opendevx_voyager_views_pre_render(ViewExecutable $view) {
  $api_type = isset($view->result[0]->_entity->field_api_type) ?
    $view->result[0]->_entity->field_api_type->value : '';
  if ($view->storage->id() == 'api_document_formatter' &&
  isset($view->field['field_document']) &&
  $api_type == VoyagerInterface::API_TYPE[1]) {
    $view->element['#attached']['library'][] =
    'opendevx_voyager/graphQL_voyager';
    $view->field['field_document']->options['type'] =
    $view->result[0]->_entity->field_api_display->value;
  }
}

/**
 * Implements hook_theme().
 */
function opendevx_voyager_theme($existing, $type, $theme, $path) {
  return [
    'voyager_ui_field_item' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function opendevx_voyager_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, VoyagerInterface::FORM_IDS)) {
    $form['field_format']['#states'] = [
      'visible' => [
        ':input[name="field_api_type"]' => ['value' => VoyagerInterface::API_TYPE[0]],
      ],
    ];
    $form['field_api_display']['#states'] = [
      'visible' => [
        ':input[name="field_api_type"]' => ['value' => VoyagerInterface::API_TYPE[1]],
      ],
    ];
  }
}
